{
  "url": "/api/test/errorMapping?test=createError501",
  "statusCode": 501,
  "statusMessage": "",
  "message": "Custom create error with 501 - message",
  "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/h3/dist/index.mjs:72:15)</span>\n<span class=\"stack\">at Object.handler (./server/api/test/errorMapping.ts:11:1)</span>\n<span class=\"stack internal\">at ./node_modules/h3/dist/index.mjs:1916:43</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:105:5)</span>\n<span class=\"stack internal\">at async ./node_modules/h3/dist/index.mjs:1988:19</span>\n<span class=\"stack internal\">at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2280:7)</span></pre>"
}
